apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway.yaml
  # Add more cluster-wide configs here:
  # - cluster-issuer.yaml
  # - resource-quotas.yaml
  # - network-policies.yaml
